apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-deployment
spec:
  replicas: 3  # Creates 3 instances (pods)
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java-app
          image: ahmedzubairu/my-java-app:latest  # Replace with your Docker image
          ports:
            - containerPort: 8080
