services:
  app:
    build:
      context: .  # The directory where the Dockerfile is located
    ports:
      - "8081:8080"  # Map host port 8081 to container port 8080
    environment:
      - SPRING_PROFILES_ACTIVE=prod  # Optional environment variables, if needed
    volumes:
      - ./logs:/app/logs  # Optional volume mapping (if needed)
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
